title: Minimal theme
logo: https://github.com/xiranwang7/My-Website/blob/master/xiran.jpg?raw=true
description: Minimal is a theme for GitHub Pages.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

