title: Xiran(Effie) Wang
logo: https://github.com/xiranwang7/My-Website/blob/master/xiran.jpg?raw=true
description: Welcome to my website!
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

