title: Xiran Wang
logo: https://raw.githubusercontent.com/xiranwang7/My-Website/master/xiran.jpg
description: "Contact me: xiranwangwork@gmail.com"
show_downloads: false
google_analytics:

#background-image: https://raw.githubusercontent.com/xiranwang7/My-Website/master/xiran.jpg
#background-position: center
#background-repeat: no-repeat
#background-size: contain

theme: jekyll-theme-minimal




