title: Xiran(Effie) Wang
logo: https://raw.githubusercontent.com/xiranwang7/My-Website/master/xiran.jpg
description: I would like to share some of my intresteing projects and little things about statistics. 
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

